#pragma once

#include <QByteArray>
#include <QDateTime>
#include <QList>
#include <QString>

namespace mole::net {

/// One row of an `ls -l` style directory listing.
///
/// Two backends need this. For SFTP the text is generated by libcurl itself out
/// of the protocol's own attributes, so the columns are dependable. For FTP it
/// comes from whatever the server felt like printing, so anything unrecognised
/// has to be discarded rather than guessed at -- which is what `valid` is for.
struct ListingRow
{
    QString name;
    bool isDir = false;
    bool isSymlink = false;
    qint64 size = 0;
    QDateTime modified;
    /// "rwxr-xr--", without the leading type character.
    QString permissions;
    QString owner;
    QString group;
    bool valid = false;
};

/// Parses one line. `valid` is false when the line is not a listing row at all
/// -- a "total 48" header, a server banner, a blank line.
///
/// `now` is passed in rather than read from the clock because a listing that
/// omits the year has to be resolved against something, and a test cannot assert
/// anything about a result that depends on today's date.
ListingRow parseListingLine(const QString& line, const QDateTime& now);

/// Parses a whole listing, dropping only the lines that are not entries.
///
/// "." and ".." are kept, and deliberately so. "." is the only row that
/// describes the node being listed, and it is what distinguishes a directory
/// from a file: asked to list a regular file, an SFTP server does not refuse --
/// it answers with a "." that is not a directory. Dropping the dot rows here
/// would throw that away and turn "this is a file" into "this is an empty
/// directory". Callers skip them with isDotEntry() once they have looked.
QList<ListingRow> parseUnixListing(const QByteArray& text, const QDateTime& now);

/// True for the "." and ".." rows a listing carries.
bool isDotEntry(const ListingRow& row);

} // namespace mole::net
